### ISSUE TITLE
FR: Right-click for background tab

### ISSUE THREAD

**Issue by Gitoffthelawn** [t7yang/right-next-browser-extension#1]
It is impressive how much functionality you created in such a small and efficient extension!  Well done!

Would is be easy to allow right-clicking to open the background tab instead of middle-clicking?

Thanks!

**Comment by t7yang** [comment]
Thank you 😀

The only mission of this extension is to make sure the new open tab place right next to current tab, but do not handle how to open a new tab (left click and middle click to open new tab is provide by browser itself).

So I suggest you use mouse gesture extension like [gesturefy](https://addons.mozilla.org/en-US/firefox/addon/gesturefy/), I'm currently using it and have very good experience. Hope this can help you.

**Comment by Gitoffthelawn** [comment]
@t7yang You're welcome!  I've been looking for an excuse to finally experiment with gesturefy... maybe this will be it! :)
