### ISSUE TITLE
網頁還在載入時用新分頁開啟連結 新分頁會開在上一個載入完成分頁的右邊

### ISSUE THREAD

**Issue by hijacker000** [t7yang/right-next-browser-extension#2]
在網頁還在載入時，此時用新分頁開啟連結，結果新分頁會開在上一個載入完成分頁的右邊
而不是在目前分頁的右邊
請看影片9秒處，新分頁是開在目前分頁的左邊
https://www.youtube.com/watch?v=eXvGpKXXcPE

**Comment by t7yang** [comment]
瞭解，那看來判斷 container 分頁的機制不能單靠載入狀態，我再思考看看這個部分要怎麼處理。

**Comment by t7yang** [comment]
更新 2.0.0 後如果有使用到 container 分頁的話，請確保給予 tabs 授權，然後再測試看看，我這裡一樣用你給的網站測試已經可以正常運作。

**Comment by hijacker000** [comment]
可以正常運作，感謝
